bitcoind:
    image: sgehrman/stellar-bitcoin
    command: -testnet -printtoconsole -prune=600 -disablewallet -rpcpassword=password -rpcuser=user -dbcache=2000 -server -rpcallowip=0.0.0.0/0
    container_name: stellar-bitcoin
    volumes:
      - /home/steve/bitcoin-test:/root
    restart: unless-stopped
    ports:
      - 18332:18332/tcp
      - 18333:18333/tcp
      - 8332:18332/tcp
      - 8333:18333/tcp
