bitcoind:
    image: sgehrman/stellar-bitcoin
    command: -testnet -printtoconsole -prune=600 -disablewallet -rpcpassword=password -rpcuser=user
    container_name: stellar-bitcoin
    volumes:
      - /home/steve/bitcoin-test:/bitcoin
    restart: unless-stopped
    ports:
      - 18332:18332/tcp
      - 18333:18333/tcp
      - 8332:18332/tcp
      - 8333:18333/tcp
