bitcoind:
    image: sgehrman/stellar-bitcoin
    command: -testnet -printtoconsole
    container_name: stellar-bitcoin
    volumes:
      - /home/steve/bitcoin-test:/bitcoin
    restart: unless-stopped
    environment:
      DISABLEWALLET: 1
      RPCPASSWORD: password
      RPCUSER: user
      TESTNET: 1
      PRUNE: 600
     ports:
      - 18332:18332/tcp
      - 18333:18333/tcp
      - 8332:18332/tcp
      - 8333:18333/tcp
